import { useState } from 'react'
import { Download, Loader } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { Trip, ItineraryEvent } from '@/lib/types'

interface PDFExportProps {
  trip: Trip
  events: ItineraryEvent[]
}

export function PDFExport({ trip, events }: PDFExportProps) {
  const [isExporting, setIsExporting] = useState(false)

  const handleExport = async () => {
    try {
      setIsExporting(true)

      // Create a hidden container for PDF content
      const container = document.createElement('div')
      container.style.position = 'absolute'
      container.style.left = '-9999px'
      container.style.width = '800px'
      container.style.background = 'white'
      container.style.padding = '40px'
      container.style.fontFamily = 'Arial, sans-serif'

      // Add content
      container.innerHTML = `
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="font-size: 32px; margin: 0; color: #1a1a1a;">${trip.title}</h1>
          <p style="font-size: 14px; color: #666; margin: 10px 0 0 0;">${trip.destination}</p>
        </div>

        <div style="margin-bottom: 30px; border-top: 1px solid #ddd; padding-top: 20px;">
          <h2 style="font-size: 18px; margin: 0 0 15px 0; color: #1a1a1a;">Trip Details</h2>
          <p style="margin: 5px 0; font-size: 13px; color: #666;">
            <strong>Destination:</strong> ${trip.destination || 'N/A'}<br/>
            <strong>Status:</strong> ${trip.status || 'Active'}<br/>
            <strong>Created:</strong> ${new Date(trip.syncedAt).toLocaleDateString()}
          </p>
        </div>

        <div style="margin-bottom: 30px; border-top: 1px solid #ddd; padding-top: 20px;">
          <h2 style="font-size: 18px; margin: 0 0 15px 0; color: #1a1a1a;">Itinerary (${events.length} events)</h2>
          ${events.map((event, idx) => `
            <div style="margin-bottom: 15px; padding: 12px; background: #f9f9f9; border-radius: 6px; border-left: 3px solid #007bff;">
              <p style="margin: 0 0 8px 0; font-size: 12px; font-weight: bold; color: #007bff; text-transform: uppercase;">${event.type}</p>
              <p style="margin: 0; font-size: 13px; color: #1a1a1a;">
                ${event.type === 'flight' ? `${event.flight?.departureAirport} → ${event.flight?.arrivalAirport}` : ''}
                ${event.type === 'hotel' ? `${event.hotel?.name || 'Hotel'}` : ''}
                ${event.type === 'activity' ? `${event.activity?.name || 'Activity'}` : ''}
              </p>
              ${event.flight?.flightNumber ? `<p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">Flight: ${event.flight.flightNumber}</p>` : ''}
              ${event.flight?.departureTimeLocal ? `<p style="margin: 4px 0 0 0; font-size: 12px; color: #666;">Departs: ${event.flight.departureTimeLocal}</p>` : ''}
            </div>
          `).join('')}
        </div>

        <div style="border-top: 1px solid #ddd; padding-top: 20px; font-size: 12px; color: #999; text-align: center;">
          <p style="margin: 0;">Generated by Travelway AI</p>
          <p style="margin: 5px 0 0 0;">${new Date().toLocaleDateString()}</p>
        </div>
      `

      document.body.appendChild(container)

      // Convert to canvas
      const canvas = await html2canvas(container, {
        backgroundColor: '#ffffff',
        scale: 2,
      })

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      const imgData = canvas.toDataURL('image/png')
      const pageHeight = pdf.internal.pageSize.getHeight()
      const pageWidth = pdf.internal.pageSize.getWidth()
      const imgHeight = (canvas.height * pageWidth) / canvas.width

      let heightLeft = imgHeight
      let position = 0

      // Add image to PDF
      pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight)
      heightLeft -= pageHeight

      // Add additional pages if needed
      while (heightLeft > 0) {
        position = heightLeft - imgHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight)
        heightLeft -= pageHeight
      }

      // Download
      pdf.save(`${trip.title.replace(/\s+/g, '_')}_itinerary.pdf`)
      toast.success('Itinerary downloaded!')

      // Cleanup
      document.body.removeChild(container)
    } catch (error) {
      console.error('PDF export error:', error)
      toast.error('Failed to export PDF')
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <Button
      onClick={handleExport}
      disabled={isExporting}
      variant="outline"
      size="sm"
      className="gap-2"
    >
      {isExporting ? (
        <>
          <Loader className="size-4 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="size-4" />
          Export PDF
        </>
      )}
    </Button>
  )
}
